<?xml version="1.0" encoding="utf-8"?><Database Name="qlythueacc1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DANH-BRUH\SQLEXPRESS;Initial Catalog=qlythueacc1;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="qlythueacc1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ADMIN" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="admin_id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="admin_password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Game" Member="Games">
    <Type Name="Game">
      <Column Name="Game_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Game_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idLoaiGame" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AnhBia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Game_OrderDetail" Member="OrderDetails" ThisKey="Game_ID" OtherKey="Game_ID" Type="OrderDetail" />
      <Association Name="Game_QLTaiKhoanChoThue" Member="QLTaiKhoanChoThues" ThisKey="Game_ID" OtherKey="Game_ID" Type="QLTaiKhoanChoThue" />
      <Association Name="TheLoaiGame_Game" Member="TheLoaiGame" ThisKey="idLoaiGame" OtherKey="idLoaiGame" Type="TheLoaiGame" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="CustID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cust_Balance" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NguoiDung_ThanhToan" Member="ThanhToans" ThisKey="CustID" OtherKey="CustID" Type="ThanhToan" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetail" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="Order_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Game_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="OrderDetail_ThanhToan" Member="ThanhToans" ThisKey="Order_ID" OtherKey="Order_ID" Type="ThanhToan" />
      <Association Name="Game_OrderDetail" Member="Game" ThisKey="Game_ID" OtherKey="Game_ID" Type="Game" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QLTaiKhoanChoThue" Member="QLTaiKhoanChoThues">
    <Type Name="QLTaiKhoanChoThue">
      <Column Name="RentAccount_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RentAccount_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Game_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Game_QLTaiKhoanChoThue" Member="Game" ThisKey="Game_ID" OtherKey="Game_ID" Type="Game" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhToan" Member="ThanhToans">
    <Type Name="ThanhToan">
      <Column Name="Payment_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rent_time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Order_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="OrderDetail_ThanhToan" Member="OrderDetail" ThisKey="Order_ID" OtherKey="Order_ID" Type="OrderDetail" IsForeignKey="true" />
      <Association Name="NguoiDung_ThanhToan" Member="NguoiDung" ThisKey="CustID" OtherKey="CustID" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoaiGame" Member="TheLoaiGames">
    <Type Name="TheLoaiGame">
      <Column Name="idLoaiGame" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiGame" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TheLoaiGame_Game" Member="Games" ThisKey="idLoaiGame" OtherKey="idLoaiGame" Type="Game" />
    </Type>
  </Table>
</Database>